### ISSUE TITLE
Interface methods do not work with Pattern objects

### ISSUE THREAD

**Issue by baron-ghost-i** [ificiana/remagic#11]
Interface methods, except `create()`, do not support `Pattern` objects, causing them to raise `TypeError` when used alongside addition and multiplication operators.

**Comment by ificiana** [comment]
@baron-ghost-i can you provide some example code?

**Comment by baron-ghost-i** [comment]
> @baron-ghost-i can you provide some example code?

## Minimal Reproducible Code
```py
import remagic as rem
test_1 = rem.WS + rem.optional(rem.WS)
test_2 = rem.optional(rem.WS) + rem.WS
```

## Expected Results
Two Pattern objects with attribute `pattern` being `'\\s\\s?'` and `'\\s?\\s'` respectively.

## Actual Results
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\site-packages\remagic\pattern.py", line 62, in __add__
    return Pattern(self._pattern + other._pattern)
TypeError: can only concatenate str (not "Pattern") to str
```
##Environment
OS: Windows 10
Python: 3.10.0

**Comment by ificiana** [comment]
I see. As for the result, I think it might be helpful if we use a non-capturing group

Or we can make it more intelligent by making it work differently for provided constants (like WS, N)

```py
optional(WS) => Pattern<r"\s?">
optional(CHAR + DIGIT) => Pattern<r"(?:.\d)?">
```
